import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './navBar'
import { Providers } from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="wrapper">
          <Providers>
          <NavBar />
            {children}
            </Providers>
        </div>
      </body>
    </html>
  )
}
